general:
  sample-metadata: metadata.csv
  patch_size: [288, 288]
  run_name: null
preprocessing:
  workdir: yadda/yadda/yadda
  filtering: pass # TODO: implement smoothing
  slicing:
    patch_dim: [5, 5]
    rotate: true
training:
  general:
    lr: 0.0001
    drop_empty: 0
    batch_size: 8
    n_filters: 4
  evaluation:
    active: true
    cv_folds: 5
    epochs: 30
    stopping_patience: 0
    tensorboard: true
    logdir: ./logs
  production:
    active: true
    epochs: 30
    model_output: ./model.ckpt
prediction:
  active: true
  model: null
  input_meta: pass.csv
  output_dir: out/
  crop: 48
  compensate_crop: true
  patch_dim: [5, 5]
