data:
  training_data: ./meta/metadata.csv
  prediction_data: ./meta/metadata.csv
  output_dir: ./out/
preprocessing:
  filtering: # e2proc3d parameters
    active: true # TODO: implement filtering
    lowpass_cutoff: .25
    highpass_cutoff: 5 # highpass cutoff in fourier space
    clamp_nsigma: 3
  slicing:
    patch_size: [288, 288]
    patch_dim: [5, 5]
    rotate: true
training:
  general:
    lr: 0.0001
    drop_empty: 0
    batch_size: 8
    n_filters: 4
  evaluation:
    active: true
    cv_folds: 5
    epochs: 30
    stopping_patience: 0 # FIX: no early stopping
    tensorboard: true
    run_name: null
    logdir: ./logs
  production:
    active: false
    epochs: 30
    model_output: ./model.h5
prediction:
  active: false
  model: null # meta/some_other_model.h5
  crop: 48
  compensate_crop: true
  patch_size: [288, 288]
  patch_dim: [5, 5]
  z_cutoff: 200

