preprocessing:
  filtering: # e2proc3d parameters
    active: true
    lowpass_cutoff: .25 # lowpass cutoff in fourier space
    highpass_cutoff: 5 # highpass cutoff in fourier space
    clamp_nsigma: 3 # n sigma cutoff after normalization
  slicing:
    patch_size: [288, 288]
    patch_dim: [5, 5]
    rotate: true
    z_stride: 5
    crop: 0
    flip_y: false
training:
  general:
    normalize: true
    lr: 0.0001
    drop_empty: 0
    batch_size: 8
    n_filters: 4
  evaluation:
    active: true
    cv_folds: 5
    epochs: 25
    stopping_patience: 0 # Disable by setting to 0
    tensorboard: true
    run_name: null
    logdir: ./logs
  production:
    active: false
    epochs: 50
    model_output: ./model.h5
prediction:
  active: false
  model: null
  normalize: true
  crop: 0
  compensate_crop: true
  patch_size: [288, 288]
  patch_dim: [5, 5]
  z_cutoff: 0
debug: false

